_format_version: "3.0"
_transform: true

services:
  - name: document-service
    url: http://document:8001
    routes:
      - name: document-route
        paths:
          - /document

  - name: drone-service
    url: http://drone:8002
    routes:
      - name: drone-route
        paths:
          - /drone

  - name: flight-service
    url: http://flight-planning:8004
    routes:
      - name: flight-route
        paths:
          - /flight

  - name: operations-support-service
    url: http://operations-support:8005
    routes:
      - name: operations-support-route
        paths:
          - /operations-support

  - name: order-service
    url: http://order:8006
    routes:
      - name: order-route
        paths:
          - /order

  - name: payment-service
    url: http://payment:8007
    routes:
      - name: payment-route
        paths:
          - /payment

  - name: user-service
    url: http://user:8008
    routes:
      - name: user-route
        paths:
          - /user

  - name: weather-service
    url: http://weather:8009
    routes:
      - name: weather-route
        paths:
          - /weather
  
  - name: book-drone-service
    url: http://book-drone:8101
    routes:
      - name: book-drone-route
        paths:
          - /book-drone

plugins:
  - name: rate-limiting
    config:
      minute: 100
      policy: local

  - name: cors
    config:
      origins:
        - "*"
      methods:
        - HEAD
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Access-Control-Allow-Origin
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type