# volume: persistent data storage for containers, managed by Docker
# define a volume "esd_rabbitmq_data" to remember RabbitMQ exchange and queues across container restarts
volumes:
  rabbitmq_data:
    name: esd_rabbitmq_data

# network: virtual network allowing Docker containers to communicate with each other and external systems
# containers on same bridge network can communicate with each other
# this code creates a network "esd-net" for RabbitMQ container
networks:
  esd-net:
    driver: bridge
    name: esd-net

services:

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management    # docker official image with tag 3-management
    hostname: esd-rabbit            # define hostname for the container. Hostname used to keep track of our data
    restart: always                 # always restart container if it stops
    ports:
      - "5672:5672"                 # 5672 used for RabbitMQ client connections
      - "15672:15672"               # 15672 used for RabbitMQ management website
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - esd-net                     # bind it to the network defined above on line 10